title: "Romagnani lab single cell analysis guides"
baseurl: /single_cell_analysis

# where things are
layouts_dir: /layouts
includes_dir: /includes
sass:
  sass_dir: /sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Introduction
    url:
  - title: scRNA-seq, 5' and 3'
    url: scRNA
  - title: ATAC-seq
    url: scATAC
  - title: Multiome/dogma
    url: multiome
  - title: Spatial
    url: spatial
